### ISSUE TITLE
broken yum after install

### ISSUE THREAD

**Issue by giadefa** [Acellera/install#1]
[root@localhost ~]# yum
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   /opt/acellera/miniconda3/lib/liblzma.so.5: version `XZ_5.1.2alpha' not found (required by /lib64/librpmio.so.3)

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

If you cannot solve this problem yourself, please go to 
the yum faq at:
  http://yum.baseurl.org/wiki/Faq

**Comment by j3mdamas** [comment]
Gianni fixed it by unsetting the `LD_LIBRARY_PATH`

**Comment by giadefa** [comment]
root should not have python and LD_LIBRARY_PATH changed

**Comment by j3mdamas** [comment]
This is fixed
